version: '3'

services:
  app:
    build: ./app
    restart: always
    ports:
      - 5000:5000
      - 3000:3000

  web:
    build: ./web
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

